export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const DETAILS_MOVIES_SUCCESS = 'DETAILS_MOVIES_SUCCESS';
export const DETAILS_MOVIES_FAILURE = 'DETAILS_MOVIES_FAILURE';
